# Generated by Django 6.0.4 on 2026-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('avg_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('count', models.IntegerField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
