# Generated by Django 6.0.4 on 2026-04-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_text', models.CharField(max_length=100)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('Jumia', 'Jumia'), ('Avito', 'Avito'), ('Amazon', 'Amazon'), ('eBay', 'eBay'), ('Other', 'Other')], default='Other', max_length=100)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('query', models.CharField(blank=True, help_text='Terme de recherche qui a produit ce produit', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source'], name='products_pr_source_ff2abd_idx'), models.Index(fields=['query'], name='products_pr_query_64ac3b_idx'), models.Index(fields=['price_value'], name='products_pr_price_v_9f3a54_idx')],
            },
        ),
    ]
